package se.liu.game.tower;

import se.liu.game.monster.MonsterType;

import java.awt.*;

/**
 * Bullet objects are generated by the gameEngine when a monsters get within the radius of a tower. Will travel to the monster and damage it
 */
public class Bullet
{
    private final Point position;
    private final Point destination;
    private int life = 0;
    private int reaperDamage;
    private int fireDamage;
    private int grassDamage;
    private int iceDamage;
    private int damage;
    private boolean poison = false;

    public Bullet(Point position, Point destination, Tower tower){
	this.position = position;
	this.destination = destination;
	if(tower.getTowerType().equals(TowerType.POISON_TOWER)){
	    poison = true;
	}
	else{
	reaperDamage = tower.getElementMultiplier(MonsterType.REAPER);
	fireDamage = tower.getElementMultiplier(MonsterType.FIRE);
	grassDamage = tower.getElementMultiplier(MonsterType.GRASS);
	iceDamage = tower.getElementMultiplier(MonsterType.ICE);
	damage = tower.getDamageLevel();
	}

    }

    public boolean isPoison() {
	return poison;
    }

    public int getDamage() {
	return damage;
    }

    public int getLife() {
	return life;
    }

    public Point getPosition() {
	return new Point(position);
    }

    public int getDamageMultiplier(MonsterType monsterType){
	switch(monsterType){
	    case REAPER -> {
		return reaperDamage;
	    }
	    case ICE -> {
		return iceDamage;
	    }
	    case FIRE -> {
		return fireDamage;
	    }
	    case GRASS -> {
		return grassDamage;
	    }
	}
	return 0;
    }


    public void move(){
	final int moveDistance = 2;
	life++;
	if(position.x < destination.x) position.x += moveDistance;
	else if(position.x > destination.x) position.x -= moveDistance;
	if(position.y < destination.y) position.y += moveDistance;
	else if(position.y > destination.y) position.y -= moveDistance;
    }



}
